### ISSUE TITLE
OAuth 2.0 프로토콜을 사용하여 SNS 아이디로 회원가입

### ISSUE THREAD

**Issue by channprj** [channprj/frieday#5]
페이스북 아이디를 기본으로 하고, 가능하면 Github 아이디로 가입도 넣어보자.

**Comment by ye-eun11** [comment]
Login form에 SNS계정 로그인 추가할까?

**Comment by channprj** [comment]
@ye-eun11 응 오늘 마무리 지을 예정임.

**Comment by channprj** [comment]
페이스북 인증과정까진 연결이 되었는데, 프로필 사진과 이메일 등을 받아오는 과정에서 계속 알 수 없는 오류가 생겨서 일단 중지된 상태. 시간 관계상 나중에 다시 시도해야 할듯.
