### ISSUE TITLE
stylesheet, javascript 선택적으로 적용하기

### ISSUE THREAD

**Issue by inhobaek** [channprj/frieday#8]
Asset Pipeline은 Javascript와 CSS 자원을 합치고 최소화 또는 압축하기 위한 프레임워크이다.
Coffeescript,Sass, ERB와 같은 언어로 이러한 자원을 작성할 수 있도록 함.  

현재상황
  `app/assets/javascripts/application.js` 에서 일괄적으로 적용하고 있는 Javascript와 `app/assets/stylesheets/application.css.scss`에서 import하고 있는 css 모두가 Application 전체에 적용되고 있다.  

변경목표
  Application의 각 기능별로 선택적으로 Javascript와 css를 적용하여 로드해야하는 자원의 수를 줄일 것.

**Comment by channprj** [comment]
알아본 결과 assets에 따로 파일을 생성해서 넣고, 해당 기능의 view 파일에서 link시키면 됨.
